apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.4.0 (c7964e7)
  creationTimestamp: null
  labels:
    io.kompose.service: consumer
  name: consumer
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: consumer
    spec:
      containers:
      - args:
        - npm
        - run
        - consumer
        - --silent
        env:
        - name: BASE_QUEUE_NAME
          value: recollect
        - name: ES_INDEX
          value: recollect-events
        - name: ES_URL
          value: http://elasticsearch:9200
        - name: PORT
          value: "3005"
        - name: QUEUE_NAME
          value: recollect-index
        - name: RABBITMQ_URL
          value: amqp://rabbitmq
        - name: RULES_API
          value: http://ruleshost:4040/api/rules
        image: localhost:5000/recollect
        name: consumer
        resources: {}
        workingDir: /usr/src/app
      restartPolicy: Always
status: {}
