version: '3'

services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - 15672:15672
      - 5672:5672
    restart: always

  elasticsearch:
    image: elasticsearch:latest
    restart: always

  kibana:
    image: kibana:5.5.0
    restart: always
    ports:
      - 5601:5601

  api:
    image: localhost:5000/recollect
    # image: recollect
    # build:
    #  context: .
    working_dir: /usr/src/app
    ports:
      - 3005:3005
    command: npm run api --silent
    restart: always
    depends_on:
      - rabbitmq
    environment:
      - PORT=3005
      - RABBITMQ_URL=amqp://rabbitmq
      - QUEUE_NAME=recollect-index
      - ES_URL=http://elasticsearch:9200
      - ES_INDEX=recollect-events
      - BASE_QUEUE_NAME=recollect
  consumer:
    image: localhost:5000/recollect
    # image: recollect
    # build:
    #  context: .
    working_dir: /usr/src/app
    command: npm run consumer --silent
    restart: always
    depends_on:
      - api
      - rabbitmq
      - elasticsearch
    environment:
      - PORT=3005
      - RABBITMQ_URL=amqp://rabbitmq
      - QUEUE_NAME=recollect-index
      - ES_URL=http://elasticsearch:9200
      - ES_INDEX=recollect-events
      - BASE_QUEUE_NAME=recollect
      - RULES_API=http://rules-api:4040/api/rules
