version: '3'

services:
  rabbitmq:
    image: rabbitmq:3.6.15-management
    ports:
      - 15672:15672
      - 5672:5672
    restart: always

  elasticsearch:
    image: elasticsearch:latest
    restart: always

  kibana:
    image: kibana:latest
    restart: always
    ports:
      - 5601:5601

  api:
    image: recollect
    build:
     context: .
    volumes:
      - ".:/usr/src/app"
    working_dir: /usr/src/app
    ports:
      - 3005:3005
    command: npm run api --silent
    restart: always
    depends_on:
      - rabbitmq
    environment:
      - APP_PORT=3005
      - RABBITMQ_URL=amqp://rabbitmq
      - QUEUE_NAME=recollect-index
      - ES_URL=http://elasticsearch:9200
      - ES_INDEX=recollect-events
      - BASE_QUEUE_NAME=recollect
  consumer:
    image: recollect
    build:
     context: .
    volumes:
      - ".:/usr/src/app"
    working_dir: /usr/src/app
    command: npm run consumer --silent
    restart: always
    depends_on:
      - api
      - rabbitmq
      - elasticsearch
    environment:
      - APP_PORT=3005
      - RABBITMQ_URL=amqp://rabbitmq
      - QUEUE_NAME=recollect-index
      - ES_URL=http://elasticsearch:9200
      - ES_INDEX=recollect-events
      - BASE_QUEUE_NAME=recollect
      - RULES_API=http://rules-api:4040/api/rules
      - MAIL_SERVICE=office365
      - MAIL_HOST=smtp.office365.com
      - MAIL_PORT=587
      - MAIL_AUTH_USER=booking@danhotels.onmicrosoft.com
      - MAIL_AUTH_PASSWORD=Linn3933
