version: '3'

services:
  rabbitmq:
    image: rabbitmq:3.6.15-management
    build: utils/docker/rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    restart: always

  elasticsearch:
    image: elasticsearch:5.6
    restart: always

  kibana:
    image: kibana:6.5.1
    restart: always
    ports:
      - 5601:5601

  api:
    build: utils/docker/recollect
    volumes:
      - "./src:/app/src"
    working_dir: /app
    ports:
      - 3005:3005
    command: |
      /bin/bash -c "
        npm run build
        npm run api"
    restart: always
    depends_on:
      - rabbitmq
    environment:
      - PORT=3005
      - APP_PORT=3005
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - QUEUE_NAME=recollect-index
      - ES_URL=http://elasticsearch:9200
      - ES_INDEX=recollect-events
      - BASE_QUEUE_NAME=recollect
  consumer:
    build: utils/docker/recollect
    volumes:
      - ".:/usr/src/app"
    working_dir: /usr/src/app
    command: npm run consumer --silent
    restart: always
    depends_on:
      - api
      - rabbitmq
      - elasticsearch
    environment:
      - APP_PORT=3005
      - RABBITMQ_URL=amqp://rabbitmq
      - QUEUE_NAME=recollect-index
      - ES_URL=http://elasticsearch:9200
      - ES_INDEX=recollect-events
      - BASE_QUEUE_NAME=recollect
      - RULES_API=http://rules-api:4040/api/rules
